name: Push to Azure Repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Azure Repo
        run: |
          AZURE_URL="https://Riteshbenjwal:${{ secrets.AZURE_GIT_TOKEN }}@dev.azure.com/Riteshbenjwal/Node/_git/Node"
          if git remote | grep -q azure; then
            git remote set-url azure $AZURE_URL
          else
            git remote add azure $AZURE_URL
          fi
          git push -u azure main --force
        env:
          AZURE_GIT_TOKEN: ${{ secrets.AZURE_GIT_TOKEN }}
