name: Push to Azure Repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Azure Repos
        run: |
          if git remote | grep -q azure; then
            git remote set-url azure https://Riteshbenjwal@dev.azure.com/Riteshbenjwal/Node/_git/Node
          else
            git remote add azure https://Riteshbenjwal@dev.azure.com/Riteshbenjwal/Node/_git/Node
          fi
          git push -u azure main
        env:
          AZURE_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_GIT_TOKEN }}
