name: Push to Azure Repo

on:
  push:
    branches:
      - main

jobs:
  sync-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Azure Repos
        run: |
          git remote add origin https://Riteshbenjwal@dev.azure.com/Riteshbenjwal/Node/_git/Node
          git push -u origin --all
        env:
          AZURE_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_GIT_TOKEN }}
